name: pokefy
description: "Pokedex App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^9.2.1

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  google_fonts: ^8.0.2

  # HTTP Client
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^7.0.1

  # Storage
#  shared_preferences: ^2.1.1
#  sqflite: ^2.4.2

  # Device Info
  package_info_plus: ^9.0.0

  # Model
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

  # State Management
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

  # Routing
  go_router: ^17.1.0

  # Additional
  intl: ^0.20.2
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/types/
    - assets/images/